# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocontentful < Formula
  desc "An Contentful Entry-Reference Mapper for Go"
  homepage "https://github.com/foomo/gocontentful"
  version "1.0.19"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/gocontentful/releases/download/v1.0.19/gocontentful_1.0.19_darwin_amd64.tar.gz"
      sha256 "f14b7cf17005a40ba291cbd76d9e50ca6404b0ac20546ad9803bc8ac45281e16"

      def install
        bin.install "gocontentful"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/gocontentful/releases/download/v1.0.19/gocontentful_1.0.19_darwin_arm64.tar.gz"
      sha256 "fa3be1669a7a02d27bb5487ce98a317ba7685546821bf603299499bf83aef775"

      def install
        bin.install "gocontentful"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/gocontentful/releases/download/v1.0.19/gocontentful_1.0.19_linux_amd64.tar.gz"
      sha256 "ff51587a46c2da709afe946b88cad004d332949a48d4f7cce6688fbfd9352da0"

      def install
        bin.install "gocontentful"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/gocontentful/releases/download/v1.0.19/gocontentful_1.0.19_linux_arm64.tar.gz"
      sha256 "cfb0e613d6085334e76c5b671b935f5415a877631acb6c64fbe7d0d3643459fa"

      def install
        bin.install "gocontentful"
      end
    end
  end

  def caveats
    <<~EOS
      gocontentful -h
    EOS
  end
end
